export const mockData = [
  {
    id: 1,
    CompanyName: "Varius Orci Institute",
    City: "High Wycombe",
    Country: "India",
    Phone: "1-926-360-4273",
  },
  {
    id: 2,
    CompanyName: "Metus In Corp.",
    City: "Puntarenas",
    Country: "Belgium",
    Phone: "1-863-593-4193",
  },
  {
    id: 3,
    CompanyName: "Ipsum Curabitur Company",
    City: "La Paz",
    Country: "Australia",
    Phone: "1-475-566-8864",
  },
  {
    id: 4,
    CompanyName: "Tellus Non PC",
    City: "Mumbai",
    Country: "Ukraine",
    Phone: "1-477-625-3174",
  },
  {
    id: 5,
    CompanyName: "Aliquet Phasellus Foundation",
    City: "Codognè",
    Country: "Italy",
    Phone: "(784) 888-8911",
  },
  {
    id: 6,
    CompanyName: "Sollicitudin Commodo Incorporated",
    City: "Götzis",
    Country: "Peru",
    Phone: "(964) 275-7731",
  },
  {
    id: 7,
    CompanyName: "Curae Phasellus LLC",
    City: "Western Water Catchment",
    Country: "Vietnam",
    Phone: "(717) 339-7318",
  },
  {
    id: 8,
    CompanyName: "Nisi A Odio Corp.",
    City: "Ipswich",
    Country: "South Africa",
    Phone: "(747) 210-7031",
  },
  {
    id: 9,
    CompanyName: "Nam Nulla Ltd",
    City: "Pamplona",
    Country: "Russian Federation",
    Phone: "(428) 778-2274",
  },
  {
    id: 10,
    CompanyName: "Sagittis Semper Incorporated",
    City: "Bastogne",
    Country: "Poland",
    Phone: "(495) 431-3227",
  },
  {
    id: 11,
    CompanyName: "Dictum Proin Corporation",
    City: "Teodoro Schmidt",
    Country: "India",
    Phone: "(556) 682-3278",
  },
  {
    id: 12,
    CompanyName: "Sed Molestie Incorporated",
    City: "Sungei Kadut",
    Country: "Canada",
    Phone: "(287) 320-7758",
  },
  {
    id: 13,
    CompanyName: "Nec Imperdiet Incorporated",
    City: "Traralgon",
    Country: "Turkey",
    Phone: "1-222-537-3120",
  },
  {
    id: 14,
    CompanyName: "Taciti Sociosqu Industries",
    City: "Torre Cajetani",
    Country: "Colombia",
    Phone: "(715) 268-4312",
  },
  {
    id: 15,
    CompanyName: "Ultrices Vivamus Limited",
    City: "Jamoigne",
    Country: "Singapore",
    Phone: "(284) 751-2510",
  },
];
